# Generated by Django 5.0.3 on 2024-03-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='product',
            new_name='storage',
        ),
    ]
