# Generated by Django 5.0.3 on 2024-03-20 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_poster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=123)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('dispatch_date', models.DateTimeField(blank=True, null=True)),
                ('unique_code', models.IntegerField(unique=True)),
                ('delivery_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'отправляется'), (2, 'доставлено')])),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
