# Generated by Django 5.0.3 on 2024-03-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'отправляется'), (2, 'доставлено'), (3, 'рассматривается')]),
        ),
    ]
